import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import av_meta


def _truncated_id3v2_mp3() -> bytes:
    # ID3v2.3 tag header: "ID3", major=3, revision=0, flags=0, size=500 bytes (synchsafe: [0, 0, 0x03, 0x74])
    # Total tag length declared = 10 + 500 = 510 bytes.
    # We only supply 50 bytes total:
    header = b"ID3\x03\x00\x00\x00\x00\x03\x74"
    partial_payload = b"COMM\x00\x00\x00\x10\x00\x00\x00engGenerated by ChatGPT"
    return header + partial_payload


def test_inspect_truncated_id3v2_reports_finding():
    data = _truncated_id3v2_mp3()
    has_c2pa, has_ai, findings = av_meta._inspect_id3v2(data)
    assert has_ai is True
    assert has_c2pa is False
    assert len(findings) > 0
    assert any("truncated" in f.lower() and "id3" in f.lower() for f in findings)


def test_inspect_truncated_id3v2_without_ai_markers_does_not_claim_ai():
    # ID3v2.3 tag header: declared 500 bytes, only 30 bytes of non-AI audio data present
    header = b"ID3\x03\x00\x00\x00\x00\x03\x74"
    partial_payload = b"TIT2\x00\x00\x00\x0a\x00\x00\x00Track 01"
    data = header + partial_payload
    has_c2pa, has_ai, findings = av_meta._inspect_id3v2(data)
    assert has_ai is False
    assert has_c2pa is False
    assert any("truncated" in f.lower() for f in findings)


def test_strip_truncated_id3v2_removes_truncated_tag():
    data = _truncated_id3v2_mp3()
    cleaned, actions = av_meta._strip_id3v2(data, strip_all_metadata=True)
    # The truncated tag should be stripped or dropped
    assert not cleaned.startswith(b"ID3")
    assert any("truncated" in a.lower() or "drop" in a.lower() for a in actions)
